# Generated by Django 5.0.1 on 2025-07-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_auth0_user_id_order_auth0_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='auth0_id',
            new_name='auth0_user_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
